before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  main: ./btget
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
archives:
- replacements:
    386: i386
    amd64: x86_64
  wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
